# Generated by Django 3.0.14 on 2022-02-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220216_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='reciptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('CNIC', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('education', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=6)),
                ('M_status', models.CharField(max_length=7)),
                ('contact', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=200)),
                ('M_start', models.TimeField()),
                ('M_end', models.TimeField()),
                ('e_start', models.TimeField()),
                ('e_end', models.TimeField()),
                ('a_start', models.TimeField()),
                ('a_end', models.TimeField()),
                ('slot_gap', models.IntegerField()),
            ],
        ),
    ]
