# Generated by Django 3.0.14 on 2022-02-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_major_reciptionist_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField()),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('major_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('contact', models.CharField(max_length=200)),
                ('CNIC', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('education', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=6)),
                ('M_status', models.CharField(max_length=7)),
                ('language', models.CharField(max_length=100)),
                ('prof_membership', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(default='Some String', max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('CNIC', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=6)),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='slots',
            old_name='M_end',
            new_name='m_end',
        ),
        migrations.RenameField(
            model_name='slots',
            old_name='M_start',
            new_name='m_start',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='p_id',
        ),
        migrations.AddField(
            model_name='reciptionist',
            name='email',
            field=models.EmailField(default='Some String', max_length=254),
        ),
        migrations.AddField(
            model_name='slots',
            name='d_id',
            field=models.IntegerField(default=0),
        ),
    ]
