# Generated by Django 3.0.14 on 2022-02-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220216_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='CNIC',
            new_name='cnic',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='M_status',
            new_name='m_status',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='CNIC',
            new_name='cnic',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='reciptionist',
            old_name='CNIC',
            new_name='cnic',
        ),
        migrations.RenameField(
            model_name='reciptionist',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='reciptionist',
            old_name='M_status',
            new_name='m_status',
        ),
    ]
