# Generated by Django 3.0.14 on 2022-02-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220217_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.major'),
        ),
    ]
