# Generated by Django 3.0.14 on 2022-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220226_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slot_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='a_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='a_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='e_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='e_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='m_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='m_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_gap',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='type',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='slots',
        ),
    ]
