# Generated by Django 3.0.14 on 2022-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220226_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='type',
        ),
        migrations.AddField(
            model_name='doctor',
            name='cfees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pfees',
            field=models.IntegerField(null=True),
        ),
    ]
