# Generated by Django 3.0.14 on 2022-03-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220307_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='d_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='h_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='major_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.major'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_id', to='api.city'),
        ),
    ]
