# Generated by Django 3.0.14 on 2022-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220314_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='block_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='block_status',
            field=models.BooleanField(null=True),
        ),
    ]
