# Generated by Django 3.0.14 on 2022-03-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220315_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='block_status',
            field=models.BooleanField(null=True),
        ),
    ]
