# Generated by Django 3.0.14 on 2022-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_hospital_block_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
