# Generated by Django 3.0.14 on 2022-03-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220318_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blocked',
        ),
    ]
