# Generated by Django 3.0.14 on 2022-03-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220320_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slot_gap',
        ),
    ]
