# Generated by Django 3.0.14 on 2022-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_getlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='account_detail',
            field=models.CharField(default='NULL', max_length=300),
            preserve_default=False,
        ),
    ]
