# Generated by Django 3.0.14 on 2022-04-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_doctor_account_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='o_proof',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='o_status',
            field=models.BooleanField(null=True),
        ),
    ]
